# Generated by Django 2.2 on 2022-10-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='One_Off_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=20)),
                ('city', models.CharField(default='Ho Chi Minh', max_length=20)),
                ('area', models.CharField(default='Area01', max_length=10)),
                ('bookdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('owntool', models.BooleanField(default=False)),
                ('feelist', models.CharField(max_length=500)),
            ],
        ),
    ]
