# Generated by Django 2.2 on 2022-10-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_one_off_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_off_fee',
            name='area',
        ),
        migrations.RemoveField(
            model_name='one_off_fee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='one_off_fee',
            name='feelist',
        ),
    ]
