# Generated by Django 2.2 on 2022-10-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20221011_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='servicecode',
            field=models.CharField(default='O_Basic_079_I', max_length=20),
        ),
    ]
