# Generated by Django 2.2 on 2022-10-11 06:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_one_off_fee_servicecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='propertydetails',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
