# Generated by Django 2.2 on 2022-10-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_one_off_fee_propertydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_off_fee',
            name='bookingID',
        ),
    ]
