# Generated by Django 2.2 on 2022-10-13 05:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_remove_one_off_fee_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Fee_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_list', jsonfield.fields.JSONField(default=dict)),
                ('name_list', models.CharField(max_length=1500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
