# Generated by Django 2.2 on 2022-10-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_service_fee_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_fee_list',
            name='name_list',
        ),
    ]
