# Generated by Django 2.2 on 2022-10-13 07:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_remove_service_fee_list_name_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_fee_list',
            name='name_lists',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
