# Generated by Django 2.2 on 2022-10-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_remove_service_fee_list_name_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_fee_list',
            name='name_lists',
            field=models.TextField(default='O_Basic_079_I'),
        ),
    ]
