# Generated by Django 2.2 on 2022-10-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_service_fee_list_name_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_fee_list',
            name='name_lists',
        ),
    ]
