# Generated by Django 2.2 on 2022-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_remove_service_fee_list_feename'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='ironingclothes',
            field=models.BooleanField(default=False),
        ),
    ]
