# Generated by Django 2.2 on 2022-11-01 07:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0016_one_off_fee_ironingclothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_One_Off_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('owntool', models.BooleanField(default=False)),
                ('ironingclothes', models.BooleanField(default=False)),
                ('servicecode', models.CharField(max_length=20)),
                ('propertydetails', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
