# Generated by Django 2.2 on 2022-11-03 01:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_test_one_off_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_one_off_fee',
            name='subscription_schedule_details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
