# Generated by Django 2.2 on 2022-11-11 07:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20221108_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='subscription_schedule_details',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='one_off_fee',
            name='urgentbooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='bookdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='servicecode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='starttime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test_one_off_fee',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_one_off_fee',
            name='propertydetails',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='test_one_off_fee',
            name='subscription_schedule_details',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
