# Generated by Django 2.2 on 2022-11-11 07:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0020_auto_20221111_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_off_fee',
            name='propertydetails',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
