# Generated by Django 2.2 on 2022-11-11 08:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0021_auto_20221111_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_off_fee',
            name='subscription_schedule_details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
