# Generated by Django 2.2 on 2022-11-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0022_auto_20221111_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='one_off_fee',
            name='subscription_schedule_details',
        ),
    ]
