# Generated by Django 2.2 on 2022-11-11 08:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0023_remove_one_off_fee_subscription_schedule_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='subscription_schedule_details',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
