# Generated by Django 2.2 on 2022-11-22 07:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0024_one_off_fee_subscription_schedule_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_one_off_fee',
            name='locationdetails',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
