# Generated by Django 2.2 on 2022-12-14 03:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0025_test_one_off_fee_locationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_one_off_fee',
            name='extra_hours_request',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
