# Generated by Django 2.2 on 2022-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0027_auto_20221214_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_one_off_fee',
            name='servicecode',
            field=models.CharField(max_length=64),
        ),
    ]
