# Generated by Django 2.2 on 2022-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0028_auto_20221214_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_one_off_fee',
            name='foreignlanguage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_one_off_fee',
            name='premiumservices',
            field=models.BooleanField(default=False),
        ),
    ]
