# Generated by Django 2.2 on 2022-12-25 19:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0029_auto_20221220_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='extra_hours_request',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='one_off_fee',
            name='foreignlanguage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='one_off_fee',
            name='locationdetails',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='one_off_fee',
            name='premiumservices',
            field=models.BooleanField(default=False),
        ),
    ]
