# Generated by Django 2.2 on 2022-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0030_auto_20221225_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_fee_list',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_fee_list',
            name='from_date',
            field=models.DateField(default='2022-12-28'),
        ),
        migrations.AddField(
            model_name='service_fee_list',
            name='to_date',
            field=models.DateField(default='2022-12-28'),
        ),
    ]
