# Generated by Django 2.2 on 2022-12-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0032_auto_20221228_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_fee_list',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='service_fee_list',
            name='to_date',
        ),
    ]
