# Generated by Django 2.2 on 2022-12-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0036_auto_20221229_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_fee_list',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
