# Generated by Django 2.2 on 2022-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0037_auto_20221229_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_fee_list',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
