# Generated by Django 2.2 on 2023-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0038_auto_20221229_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_one_off_fee',
            name='handwashclothes',
            field=models.BooleanField(default=False),
        ),
    ]
