# Generated by Django 2.2 on 2023-02-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0039_test_one_off_fee_handwashclothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='handwashclothes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_one_off_fee',
            name='numberofworkers',
            field=models.IntegerField(default=0),
        ),
    ]
