# Generated by Django 2.2 on 2023-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0040_auto_20230228_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='numberofworkers',
            field=models.IntegerField(default=0),
        ),
    ]
